# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.0.0-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-root-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-root-
      - restore_cache:
          keys:
          - v1-dependencies-app-{{ checksum "app/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-app-

      - run: yarn

      - save_cache:
          paths:
            - yarn.lock
            - node_modules
          key: v1-dependencies-root-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - app/yarn.lock
            - app/node_modules
          key: v1-dependencies-app-{{ checksum "app/package.json" }}
        
      - run: yarn lint
      - run: xvfb-run -e /dev/stdout -a npm run build
